plugin-prefix: '&6&lCB &7&l>> &r'
auto-create-races: true
race-delay: 1200
notify-on-login: true
minimum-players: 0
allow-creative: true
#dddddd
ignored-commands:
  - /pm
  - /r
disabled-worlds:
  - customworld
  - customworld2

mysql:
  enabled: false
  host: 'localhost'
  port: '3306'
  database: 'chatbrawl'
  username: 'root'
  password: 'wouter'