name: ChatBrawl
version: 1.7.3
main: be.woutzah.chatbrawl.ChatBrawl
api-version: 1.13
authors: [Woutzah]
description: A fun chat competition plugin.
softdepend: [PlaceholderAPI, LangUtils]
commands:
  cb:
    description: main chatbrawl command
    usage: /cb
    aliases: chatbrawl